services:
  db:
    image: postgres:16
    container_name: seller_db
    environment:
      POSTGRES_DB: seller_dashboard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: seller_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://admin:123456@db:5432/seller_dashboard

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: seller_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: